spring:
  profiles:
    active: dev

server:
  port: 9999
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:note
    username: admin
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration/h2
---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://notesmanagementsystem.cos2rygghoik.us-east-1.rds.amazonaws.com:5432/NMS
    username: ${USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      generate-ddl: false
      hibernate:
        ddl-auto: validate
  flyway:
    locations: classpath:db/migration/postgre