spring:
  profiles:
    active: mysql

server:
  port: 9999
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:nms
    username: admin
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://notesmanagementsystem.cos2rygghoik.us-east-1.rds.amazonaws.com:5432/NMS
    username: ${USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/nms?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDateTimeCode=false&amp&serverTimezone=UTC&createDatabaseIfNotExist=true&autoReconnect=true
    username: ${USER_NAME}
    password: ${DB_PASSWORD}
  jpa:
   show-sql: true
   open-in-view: false
   hibernate:
     ddl-auto: create